### ISSUE TITLE
Add info container with contents generated based on the faculty selection dropdown

### ISSUE THREAD

**Issue by jupjarvi** [UniversityOfHelsinkiCS/kliksutin#123]
If content is empty, do not show container.

The container should be a few rows of text, shown below the dropdown when the selection is made. The content will mainly be links to external documents.

**Comment by HRemonen** [comment]
https://github.com/UniversityOfHelsinkiCS/kliksutin/blob/b41bd52d93144e0d63000031ab50b07880253e5c/src/client/util/organisations.ts#L22
