### ISSUE TITLE
Admin view to add/remove tools

### ISSUE THREAD

**Issue by jupjarvi** [UniversityOfHelsinkiCS/kliksutin#125]
It should be possible to add new tools, remove existing tools and edit the information linked to tools within the admin view.

This should include the possibility to edit the learning types associated with each tool. The text editor should allow for creation of hyperlinks within the text as well as linking from the name of the tool (=title)

**Comment by HRemonen** [comment]
The first part is ready for review.
Second part is extracted to own issue
