### ISSUE TITLE
New question about assessment

### ISSUE THREAD

**Issue by jupjarvi** [UniversityOfHelsinkiCS/kliksutin#130]
Create a new question about assessment as the last question in the questionnaire:

"Miten kurssi arvioidaan?"
-> Hyväksytty / hylätty
-> Arvosana

**Comment by jupjarvi** [comment]
Check if this could be pre-filled from Sisu while also being editable in the questionnaire.

**Comment by HRemonen** [comment]
Question is created into the questionaire. 
Sisu exploration is moved to issue #122

**Comment by HRemonen** [comment]
Questions can now be created from the admin view
